import { addPublicationJsonLd } from "@/libs/seo/addPublicationJsonLd";
import { getAutogeneratedPublicationOG } from "@/libs/social/og";
import Head from "next/head";

const SeoHome = ({ publication }: { publication: any }) => {
  console.log("publication", publication);
  return (
    <Head>
      <title>{publication.title}</title>
      <meta
        name="description"
        content={
          publication.descriptionSEO ||
          publication.title ||
          `${publication.author.name}'s Blog`
        }
      />
      <meta property="twitter:card" content="summary_large_image" />
      <meta
        property="twitter:title"
        content={
          publication.displayTitle ||
          publication.title ||
          "Hashnode Blog Starter Kit"
        }
      />
      <meta
        property="twitter:description"
        content={
          publication.descriptionSEO ||
          publication.title ||
          `${publication.author.name}'s Blog`
        }
      />
      <meta
        property="og:image"
        content={
          publication.ogMetaData.image ||
          getAutogeneratedPublicationOG(publication)
        }
      />
      <meta
        property="twitter:image"
        content={
          publication.ogMetaData.image ||
          getAutogeneratedPublicationOG(publication)
        }
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(addPublicationJsonLd(publication)),
        }}
      />
    </Head>
  );
};

export default SeoHome;
