import Posts from "@/components/ Blogs";
import BentoCard, {
  BentoContainer,
  BentoFlavicon,
  BentoImage,
  BentoSubtitle,
  BentoText,
  BentoTitle,
} from "@/components/BentoCard";
import { ModeToggle } from "@/components/ThemeToggle";
import { Card, CardContent } from "@/components/ui/card";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel";
import { fetchData } from "@/lib/datafetch/getHome";
import { getAutogeneratedPublicationOG } from "@/lib/social/og";
import { Github } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

export async function generateMetadata() {
  const staticdata = await fetchData();

  const publication = staticdata.data.publication;

  return {
    title: publication.title,

    description:
      publication.descriptionSEO ||
      publication.title ||
      `${publication.author.name}'s Blog`,
    openGraph: {
      title: publication.title,
      description: publication.descriptionSEO,

      authors: [publication.author.name],
      images: publication.ogMetaData.image,
      locale: "en_US",
      type: "website",
    },

    twitter: {
      title: publication.displayTitle || publication.title,
      description:
        publication.descriptionSEO ||
        publication.title ||
        `${publication.author.name}'s Blog`,
      card: "summary_large_image",
      images: {
        url:
          publication.ogMetaData.image ||
          getAutogeneratedPublicationOG(publication),
        alt: publication.displayTitle || publication.title,
      },
    },
    icons: {
      icon: publication.favicon,
    },
  };
}
export default function Home() {
  return (
    <div className="flex flex-row gap-20 lg:gap-0  justify-between  items-start    max-md:flex-col max-md:items-center ">
      <div className=" mr-28 max-md:mr-0  relative  lg:sticky top-24 max-lg:justify-start max-w-[320px] max-h-[500px]  justify-center items-center flex">
        <Posts />
      </div>

      <div className=" flex flex-col w-full text-left  no-scrollbar py-24 ">
        <div className="  flex gap-[20px] flex-col md:flex-row justify-center md:justify-normal items-center">
          <BentoCard
            isLink={true}
            href="https://biomathcode.com"
            className=" animate-in fill-mode-both fade-in slide-in-from-bottom-11  duration-500 delay-700 "
            type="large"
            border="none"
          >
            <BentoContainer type="large">
              <div className="flex flex-col h-full justify-between">
                <div className="flex gap-3 flex-col">
                  <BentoFlavicon />
                  <BentoTitle>
                    Pratik Sharma - Web Developer from New Delhi
                  </BentoTitle>
                  <BentoSubtitle>coolhead.in</BentoSubtitle>
                </div>
                <BentoImage src="/og.jpeg" alt="Profile Image" type="large" />
              </div>
            </BentoContainer>
          </BentoCard>
        </div>

        <Link
          href={"#projects"}
          className="mt-10 font-semibold text-2xl items-center flex gap-1"
        >
          <div className="font-sm text-neutral-500">{"##  "}</div>
          Project Showcase
        </Link>

        {/* 
        <div className="flex gap-[20px]  flex-col md:flex-row justify-center md:justify-normal items-center">
          <BentoCard
            type="vertical"
            className="relative"
            rounded={true}
            border="1px solid #eee"
          >
            <div className="absolute bottom-0 left-0 right-0 top-0 bg-[radial-gradient(circle_800px_at_100%_200px,#d5c5ff,transparent)]"></div>
          </BentoCard>
          <div className="flex flex-col gap-[20px]">
            <BentoCard
              type="long"
              className="relative"
              rounded={true}
              border="1px solid #eee"
            >
              <div className="absolute bottom-0 left-0 right-0 top-0 rotate-180 transform bg-white bg-[radial-gradient(60%_120%_at_50%_50%,hsla(0,0%,100%,0)_0,rgba(252,205,238,.5)_100%)]"></div>
            </BentoCard>
            <div className="flex gap-5">
              <BentoCard
                type="small"
                className="relative"
                rounded={true}
                border="1px solid #eee"
              >
                <div className="absolute bottom-0 left-0 right-0 top-0  bg-[rgba(173,109,244,0.5)] "></div>
              </BentoCard>
              <BentoCard
                type="small"
                className="relative"
                rounded={true}
                border="1px solid #eee"
              >
                <div className="absolute bottom-0 left-0 right-0 top-0 rotate-180 transform bg-white bg-[radial-gradient(60%_120%_at_50%_50%,hsla(0,0%,100%,0)_0,rgba(252,205,38,.5)_100%)]"></div>
              </BentoCard>
            </div>

            <BentoCard
              type="long"
              className="relative"
              rounded={true}
              border="1px solid #eee"
            >
              <div className="absolute bottom-0 left-0 right-0 top-0 rotate-180 transform bg-white bg-[radial-gradient(60%_120%_at_50%_50%,hsla(0,0%,100%,0)_0,rgba(252,205,238,.5)_100%)]"></div>
            </BentoCard>
          </div>
        </div> */}
      </div>
    </div>
  );
}
